package com.codename1.apps.sslserverchecker;


import com.codename1.components.SpanLabel;
import com.codename1.components.ToastBar;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.security.certfingerprint.CheckCert;
import com.codename1.ui.Button;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class SSLServerChecker {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Check Server", BoxLayout.y());
        TextField url = new TextField("https://www.codenameone.com/", "URL", 20, TextField.URL);
        TextArea result = new TextArea(3, 80);
        result.setHint("Results...");
        Button test = new Button("Test Fingerprint");
        test.addActionListener(e -> {
            try {
                String f = CheckCert.getFingerprint(url.getText());
                result.setText(f);
            } catch(IOException err) {
                ToastBar.showErrorMessage(err.getMessage());
            }
        });
        hi.add(new SpanLabel("Type in the URL and press the test fingerprint button")).
                add(url).
                add(test).
                add(result);
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
